### ISSUE TITLE
manual GPS location for weather 

### ISSUE THREAD

**Issue by fgr1986** [DRG-developer/DRG-Nathos#1]
Hi! I just noticed that no option to manually set the gps location for the weather is available at the bottom of the page.
Thanks, and great watchface!

**Comment by DRG-developer** [comment]
Oh, sorry!
I am on vacation at the moment, but i'll try to fix it as soon as possible.
I never got to implementing that feature, but it should be quite simple really.

With regards, drg developer

**Comment by DRG-developer** [comment]
I did some work, i will finish it in 3 weeks when i am home near my computer

**Comment by DRG-developer** [comment]
okay, so, got to work.
but then i realized: why would you want this? you request a gps location once, and then it will be remembered forever? if you want this, i will still implement this, but otherwise, i will delete it, because it will have a (albeit minimal) impact on battery

**Comment by fgr1986** [comment]
Hi. Apparently on the vivoactive 4 the gps request was not stored ever. So unless you are running it would not get the location

**Comment by DRG-developer** [comment]
hmm, what version are you on? 
i have never had anyone report that, all people responded with "works thanks!". 
v4.3 should keep the weather data (pusing to github in 5 min) between scrolling through widgets, so please upgrade.

**Comment by fgr1986** [comment]
Latest version finally updated the location after 1h sport, thanks. However now it only shows a rectangle instead the icon with the weather. How to download the font?

**Comment by fgr1986** [comment]
And also today when I woke up it just keep saying "noData"

**Comment by DRG-developer** [comment]
do you have a phone connection? i think that might be it?

**Comment by DRG-developer** [comment]
you can temporarile enable the bt icon in the settings, bottom of the page, to see if your phone is connected. after 3 times no new data, it will go blank. if you set the time interval to 15 minutes, it will go blank after 45 minutes. if you set it to 30 min, it will go blank after 1:30 hours

**Comment by fgr1986** [comment]
Yes, bt is always there. Anyway I can get logs?

**Comment by DRG-developer** [comment]
logs? no, you can't, connectiq logs log only crashes.

**Comment by fgr1986** [comment]
How could I assist you to debug the issue?

**Comment by DRG-developer** [comment]
are you on the latest version?

this is just so weird. i know at leat 4 people with a venu, where it works fine? 
do other watchfaces with weather work fine?
fore example, crystal or infocal? (those are free)

**Comment by fgr1986** [comment]
I am on 4.3 (or at least that is what says on the phone app). Yes, other faces (just tried one) worked fine :S

Now I have the data shown, and the correct icon. Not sure what the problem could be. I am on Android 10, latest phone app, latest vivoactive 4 FW. If it is too much work forget about it, do not want to steal your time. But just in case anybody else was also experiencing the issue.

**Comment by DRG-developer** [comment]
this is so weird?

but i am afraid that setting a manual GPS location will not fix this issue. i think the the communication with the phone is...

**Comment by DRG-developer** [comment]
maybe you need to uninstall the app and reinstall?

**Comment by fgr1986** [comment]
Connect or IQ?
I wonder if we could though, somehow, to log the attempts of communication.

**Comment by DRG-developer** [comment]
no, i mean the watchface. i could send you a PRG file, with logging on? then we can see where it fails.

also, a new WF is just arround the corner. maybe that'll work.

**Comment by DRG-developer** [comment]
you'd have to connect your device to your computer, as mass storage, and then put the PRG file under APPS, and then you switch watchfaces to that PRG file. then you use it, and after that you can view the log under LOGS, which you could send to me for analasys

**Comment by fgr1986** [comment]
cool! or if it is already in the repo, if you tell me how to compile it I can generate the PRG

**Comment by DRG-developer** [comment]
for me it would be best if i create a custom PRG. if you have the garmin SDK, and you know how to generate a dev key, then you can compile it yourself?

**Comment by fgr1986** [comment]
didn't even know I needed a dev key, so fine with the PRG. If you could just name the watchface name param differently, like testing, to later remove etc. Thanks a lot!

As I said, if it is too much work do not bother.

**Comment by DRG-developer** [comment]
no, no such thing as too much work :) i should spend at least 30 min on this from the donation, and in 10 minutes a PRG should be ready.

**Comment by DRG-developer** [comment]
here a zip file with the PRG.

[vivo4Testing.zip](https://github.com/DRG-developer/DRG-Nathos/files/5028672/vivo4Testing.zip)

**Comment by DRG-developer** [comment]
what OS do you use?

for windows, it'll work out of the box, on linux: depends on distro, debian with pcmanfm works fine, on void it doesnt.

for macos you need android file transfer

**Comment by fgr1986** [comment]
I can do it either ubuntu or windows. Will do it as soon as I get home. Thanks

**Comment by DRG-developer** [comment]
windows works the simpelest AFAIK. though ubuntu is the superior OS ofcourse.

there will be a folder called GARMIN and under that folder there'll be a folder called APPS, and under APPS, there'll be a few PRG files and a folder called LOGS. you need to create a file called vivoTesting.TXT. best would be if you rename the prg file to TEMP.PRG and then under logs create a file called TEMP.TXT because i don't know how garmin handles prg files.

i also don't even know if weather will work with  a custom PRG, but 90% chance.

**Comment by fgr1986** [comment]
logfile is empty, after 2 hours use. Path where I created TEMP.TXT: `PC\vívoactive 4\Primary\GARMIN\APPS\LOGS`

**Comment by DRG-developer** [comment]
but did you rename the prg file?

**Comment by DRG-developer** [comment]
also, was the default field weather?

**Comment by DRG-developer** [comment]
the log file should fill within seconds, and after 30 minutes should be ready.
the prg file should be named TEMP.prg and you should set the watchface to the most bottom one (aka, the prg)

**Comment by fgr1986** [comment]
Yes, I renamed the prg file, and the field appeared with the "noData" message.

**Comment by fgr1986** [comment]
Might be a permissions issue on the file? I can place a file there but do not handle writeability

**Comment by DRG-developer** [comment]
the file i still empty you mean? because even with no data, response codes, background data, recieved data by the onBGdata recieve function, and the data the main thread gets is logged

**Comment by fgr1986** [comment]
Yes, 0bytes.
After greping, only logs that appear are system ones under `vívoactive 4\Primary\GARMIN\EVNTLOGS` with name like `00000014.TXT` but I assume this one is system log, right?

**Comment by DRG-developer** [comment]
yes. are you sure you switched to the PRG watchface? maybe set the background to green for the connectIQ face, so you're sure you aren't confusing watchfaces?

**Comment by fgr1986** [comment]
It is the one you sent, for sure: it appears as development watch face.

**Comment by DRG-developer** [comment]
this is really weird. at the moment i am wondering if it isn't your device that's faulty. but then, why do other faces work? at this point i might just as well print the data on screen...

**Comment by fgr1986** [comment]
No worries, really. I have made you invest too much time. Will close the issue, and try your next watchface 👍 
Thanks for the support in any case!
